---
- name: prepare nodes
  hosts: nodes

  vars_files:
    - vars/vars.yml
  
  roles:
    - prepare-infra

- name: config master
  hosts: masters

  vars_files:
  - vars/vars.yml

  roles:
    - setup-master

- name: install ISTIO
  hosts: 127.0.0.1
  connection: local 

  vars_files:
    - vars/vars.yml

  roles:
#    - install-operator
